module.exports = {
  VERIF_USER:"VERIF_USER",
  USER_CONNECTED:"USER_CONNECTED",
  USER_DISCONNECTED:"USER_DISCONNECTED",
  MESSAGE_SENT:"MESSAGE_SENT",
  MESSAGE_RECEIVED:"MESSAGE_RECEIVED",
  DISCONNECT:"DISCONNECT",
  ROOM_CHAT: "ROOM_CHAT"
}
